extends:
  - recommended

rules:
  operation-operationId-unique:
    enabled: false
    severity: off

  path-not-include-query:
    severity: off

  no-path-trailing-slash:
    severity: off

  operation-4xx-response:
    enabled: false
    severity: off

  spec:
    severity: off

  info-license:
    severity: off
